import os
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel
import structlog
from typing import List, Optional, Dict, Any
import asyncio

from services.disease.disease_normalizer import normalize_disease_name
from services.disease.database_searchers import search_all_databases
from services.disease.uniprot_mapper import map_genes_to_uniprot
from services.disease.excel_writer_disease import write_disease_results

log = structlog.get_logger(__name__)
router = APIRouter(prefix="/api/disease", tags=["disease"])

class DiseaseQuery(BaseModel):
    query: str

class Target(BaseModel):
    symbol: str
    uniprot_id: Optional[str]

class DiseaseInfo(BaseModel):
    name: str

class DiseaseResponse(BaseModel):
    status: str
    error: Optional[str] = None
    disease_info: Optional[DiseaseInfo] = None
    targets: Optional[List[Target]] = None

@router.post("/analyze", response_model=DiseaseResponse)
def analyze_disease(payload: DiseaseQuery):
    """
    Wraps the user's synchronous disease modules to return structured JSON data to the frontend.
    """
    try:
        query = payload.query.strip()
        if not query:
            raise ValueError("Query cannot be empty")
            
        # 1. Normalize
        normalized = normalize_disease_name(query)
        if not normalized or not normalized.get("preferred_name"):
            return DiseaseResponse(status="failed", error="Failed to normalize disease name.")
            
        # 2. Database Search
        gene_results = search_all_databases(normalized)
        
        # 3. Aggregate all unique genes
        all_genes = set()
        for res in gene_results:
            all_genes.update(res.get('genes', []))
            
        # 4. Map to UniProt
        uniprot_mapping = map_genes_to_uniprot(list(all_genes))
        
        # Format response expected by the frontend table
        targets = []
        for gene in all_genes:
            targets.append(Target(
                symbol=gene,
                uniprot_id=uniprot_mapping.get(gene)
            ))
            
        return DiseaseResponse(
            status="success",
            disease_info=DiseaseInfo(name=normalized.get("preferred_name")),
            targets=targets
        )
    except Exception as e:
        log.error("Disease analysis failed", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/export_excel")
def export_excel(payload: DiseaseQuery):
    """
    Runs the full pipeline and serves the Excel file generated by write_disease_results.
    """
    try:
        query = payload.query.strip()
        if not query:
            raise ValueError("Empty query")
            
        normalized = normalize_disease_name(query)
        gene_results = search_all_databases(normalized)
        
        all_genes = set()
        for res in gene_results:
            all_genes.update(res.get('genes', []))
            
        uniprot_mapping = map_genes_to_uniprot(list(all_genes))
        
        # Write to disk using the user's logic
        output_file_path = write_disease_results(
            disease_name=query,
            normalized_disease=normalized,
            gene_results=gene_results,
            uniprot_mapping=uniprot_mapping
        )
        
        if not output_file_path or not os.path.exists(output_file_path):
            raise ValueError("Excel file generation failed.")
            
        return FileResponse(
            path=output_file_path,
            filename=os.path.basename(output_file_path),
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
    except Exception as e:
        log.error("Excel export failed", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))
